config/routes.rb
Rails.application.routes.draw do
  get 'landing_page/index'
  devise_for :users
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root to: redirect("/projects")
  root 'landing_page#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def after_sign_in_path_for(resource)
      "/projects"
    end

    def configure_permitted_parameters
      attributes = [:name, :admin, :email, :password, :password_confirmation]
      devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
      devise_parameter_sanitizer.permit(:account_update, keys: attributes)
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :check_auth
  before_action :set_project, only: %i[ show edit update destroy ]

  def check_auth
      unless user_signed_in?
          redirect_to :controller => :landing_page
      end
  end
  
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        # format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.html { redirect_to projects_url, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:author, :name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/landing_page/index.html.erb
<div class="text-center">
    <%= image_tag("freecamp.jpg.webp", maxwidth: "100%", height: "500em", alt: "logo") %>
    <div class="logo-text">BASECAMP</div>
    <a style="width: 20%" class="btn btn-primary btn-lg" href="/users/sign_in">Login</a>
    <a style="width: 20%" class="btn btn-outline-primary btn-lg" href="/users/sign_up">Sign Up</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basecamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
    <nav class="navbar navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="#">
        <img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
        Basecamp
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link">Logged in as <strong><%= current_user.email %></strong></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/projects/new">+ Add Project</a>
            </li>
            <li class="nav-item">
              <%= link_to '⚙ Edit Profile', edit_user_registration_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "🚪 Log Out", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
            <li>
        </ul>
      </div>
    </nav>
  <% end %>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="display: none">
    <%= form.text_field :author, class: "form-control", value: current_user.email %>
  </div>

  <div>
    <%= form.label :name, class: "form-label", style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, class: "form-label", style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="text-center" style="margin-top: 10px">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="card card-block text-start">    
  <div class="card-header clearfix">
    <p class="card-text text-center">
      <a class="project-name"><%= project.name %></a>
      <% if current_user.email == project.author %>
        <%= link_to "✎", edit_project_path(project), class: "btn btn-primary float-end" %>
      <% end %>
    </p>
  </div>
  <h6 class="card-subtitle  text-muted float-end" style="padding: 10px 0 0 10px">author: <%= project.author %></h6>
  <div class="card-body">
    <%= project.description %>
    <% if current_user.email == project.author %>
      <%= button_to "🗑", project, method: :delete, class: "btn btn-danger float-end" %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="col-lg-6 offset-lg-3">
  <h1 class="text-center">Editing project</h1>

  <%= render "form", project: @project %>

  <br>
<div>

<div class="text-center">
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<h1 style="text-align: center; margin-top: 20px">Projects</h1>

<div id="projects container" style="margin-top: 20px">
  <div class="row">
    <div class="col-sm all-project text-center">
      <button style="width: 80%" type="button" class="btn btn-outline-secondary">✲ All projects</button>
      <% @projects.each do |project| %>
        <% if project.author != current_user.email%>
          <%= render project %>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm my-project text-center">
      <button style="width: 80%" type="button" class="btn btn-outline-secondary">🖊 Created by me</button>
      <% @projects.each do |project| %>
        <% if project.author == current_user.email%>
          <%= render project %>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm shared-project text-center">
      <button style="width: 80%" type="button" class="btn btn-outline-secondary">👥 Shared with me</button>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="col-lg-6 offset-lg-3">
  <h1 class="text-center">New project</h1>

  <%= render "form", project: @project %>

  <br>
</div>

<div class="text-center">
  <%= link_to "Back to projects", projects_path, class: "btn btn-outline-primary" %>
</div>

app/views/projects/show.html.erb
<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>